### ISSUE TITLE
No longer popups for local files

### ISSUE THREAD

**Issue by epich** [melink14/rikaikun#2173] opened 2024-08-26 01:04 UTC
This stopped working today on local files opened in Chrome via file://. I see Japanese words highlighted like usual, but no popup with the definitions. I still have "Allow access to file URLs" enabled for the extension. Restarting Chrome didn't work. Visiting pages on the web it works fine however.

OS: Linux Mint 22
Browser: Chrome Version 127.0.6533.72 (Official Build) (64-bit)
Rikaikun: 3.0.0

I also tried in Brave which still has Rikaikun version 2.5.61. This works fine on local files.

**Comment by melink14** [comment] 2024-08-26 01:31
I was able to repro and the cause was not correctly specifiying file URLs in the new MV3 whitelist for accessing files from browser pages. I have a fix working locally so should be out soon, assuming now review delays.

Thanks for reporting!

**Comment by epich** [comment] 2024-08-26 02:20
Thanks for the quick fix!

**Comment by melink14** [comment] 2024-08-26 06:56
Fixed by #2174

Will be published tonight.

**Closed by melink14** 2024-08-26 06:56 UTC
Labels: bug
