### ISSUE TITLE
Sometimes Rikaikun does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#77] opened 2015-06-13 01:09 UTC
```
Sometimes Rikaikun is not showing any translation at all. For example, try to 
read the last paragraph of this article:

http://headlines.yahoo.co.jp/hl?a=20120522-00000307-yom-soci

This happens not often but regularly.


```

Original issue reported on code.google.com by `marco.pe...@gmail.com` on 22 May 2012 at 6:23

**Comment by melink14** [comment] 2022-07-07 08:04
Duplicate of #108

**Closed as completed by melink14** 2022-07-07 08:04 UTC
Labels: Type-Defect, auto-migrated, P2
