### ISSUE TITLE
Feature request: Japanese Dictionary

### ISSUE THREAD

**Issue by timsts** [melink14/rikaikun#123] opened 2016-08-12 06:13 UTC
Thank you for the chrome port.  I really love it, especially since I am using a chromebook and cant use anything else.

Is it anyway possible to have an option to use Japanese definitions instead of English definitions.  I know I can turn off the English by pressing D or going into the settings, but having the Japanese definition readily available would be great.  It's an option in rikaichan, but not rikaikun.

Thanks
-Tim

**Comment by vintotal** [comment] 2017-01-23 01:25
Je suis intéressé aussi, je voudrais utiliser le dictionnaire français. :-)

**Comment by melink14** [comment] 2020-07-25 12:56
Duplicate of #146

**Closed by melink14** 2020-07-25 12:56 UTC
Labels: 2018 triaged, enhancement
