### ISSUE TITLE
Rikaikun settings not saving (again)

### ISSUE THREAD

**Issue by phreakymonkey** [melink14/rikaikun#396] opened 2021-04-05 07:45 UTC
**Describe the bug**
This was previously an issue that seemed to have been fixed late last year, but "Highlight text" keeps enabling itself and won't stay off. The last time it happened I posted a review, to which Erek responded: "There was a bug which doesn't allow changing default true options to false." So I assume it's probably the same thing again?

**To Reproduce**
Disable "Highlight text" (or probably change any default setting, I dunno).

**Expected behavior**
It should stay off.

**System details (OS, browser version, rikaikun version)**
- OS: macOS Catalina
- Browser Version: Chrome 89.0.4389.114
- rikaikun Version: It reports itself as 1.0.0

**Comment by melink14** [comment] 2021-04-05 08:55
I actually never fixed that bug so you might have just went awhile without noticing it (or another issue is presenting itself).

To be clear, the bug is that whenver you restart chrome or your computer your setting reverts?

If so then it's covered by #346

**Comment by phreakymonkey** [comment] 2021-04-05 09:03
Really? I could have sworn it was back to normal for the last couple months.

Restarting Chrome resets the setting. No reboot is required to reproduce it.

**Comment by melink14** [comment] 2021-04-05 09:13
Yeah, it definitley was never fixed... I only mention rebooting since for many people that's the only time chrome restarts.

**Comment by melink14** [comment] 2021-04-05 09:14
Duplicate of #346

**Closed by melink14** 2021-04-05 09:14 UTC
Labels: bug
