### ISSUE TITLE
Add new dictionary file

### ISSUE THREAD

**Issue by tokyokamera** [melink14/rikaikun#702] opened 2021-09-24 02:34 UTC
I would really like to use a Japanese - French dictionary.
How convert dict.sqlite to .dat & .idx file?

**Comment by melink14** [comment] 2021-09-24 05:04
Where did you get the dict.sqlite file? Is it a conversion of the french entries from edict? http://ftp.edrdg.org/pub/Nihongo/00INDEX.html

Handling other dictionaries in general is covered by #185 (epwing specifically by #146) so I'll dupe this over there so I can include information about which formats you need for your french dictionary.

**Comment by tokyokamera** [comment] 2021-09-27 12:37
Thank you so much for your response to my request for information.

https://www.polarcloud.com/down/mdo/rikaichan-nl-2-01-210901.xpi
Rename file to .zip and unzip it, you find dict.sqlite

I looked #185 and #146 but I still have not found a solution to the problem.

**Comment by melink14** [comment] 2021-09-27 13:52
Ah, I see; that's the old discontinued Rikaichan's format; I'm guessing it comes from EDRDG (but is out of date) so there should be equivalent eventually.

#185 doens't solve your problem now but is just where I'm tracking problem to allow additional dictionaries. I'll close this as a dupe of #185 so follow there if you want updates.

It probably won't be done soon due to other priorities so sorry for the inconvenience.

Creating the .dat and .idx files is done in https://github.com/melink14/rikaikun/blob/main/utils/update-db.ts so you may be able to convert the french data but since that script expects edict format and French is only available in other formats it won't be very easy. :(

**Comment by melink14** [comment] 2021-09-27 13:52
Duplicate of #185

**Closed by melink14** 2021-09-27 13:52 UTC
Labels: enhancement
