### ISSUE TITLE
Add an ability to paste text into rikaikun and convert to a bubbable html element.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#21] opened 2015-06-13 01:09 UTC
```
Right now, rikaikun can't work with text area's and the like, which people 
like to use for translating their own text.

Instead, I propose adding a feature to take any text, give it to rikaikun, 
and rikaikun will make a div containing the text which can then be read using 
rikaikun.
```

Original issue reported on code.google.com by `melin...@gmail.com` on 8 Jan 2010 at 7:26

**Comment by melink14** [comment] 2022-07-15 01:04
Duplicate of #18

**Closed by melink14** 2022-07-15 01:04 UTC
Labels: auto-migrated, Type-Enhancement, P2
