### ISSUE TITLE
Can't Load Dictionary Files Like in Rikaichan

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#5] opened 2015-06-13 01:08 UTC
```
Rikaichan has this great functionality where you load dictionaries via 
another extension and then it's used by the main program.

Right now this isn't available and the main dictionary is hardcoded in.  By 
1.0 I'll have this implemented.
```

Original issue reported on code.google.com by `melin...@gmail.com` on 5 Jan 2010 at 7:50

**Comment by melink14** [comment] 2020-07-25 13:11
Duplicate of #185

**Closed by melink14** 2020-07-25 13:11 UTC
Labels: Milestone-Release1.0, Priority-Medium, Type-Defect, auto-migrated
