### ISSUE TITLE
Google Translate box, curser not accurate

### ISSUE THREAD

**Issue by Baardman82** [melink14/rikaikun#402] opened 2021-04-14 11:13 UTC
**When trying to use Rikaikun in a Google translate window, the curser has to be 3 to 4 characters to the left to pick up the word I want it to pick up. Second line doesn't want to work at all, it only grabs the first word in the top line.**

Microsoft Windows 10 Pro
Google Chrome browser Version 89.0.4389.114 (Official Build) (64-bit)
Rikaikun Version 1.0.0

![Top line](https://user-images.githubusercontent.com/82510978/114701490-d8d09600-9d5d-11eb-84fb-69097064ec19.jpg)
![Second line](https://user-images.githubusercontent.com/82510978/114701509-dcfcb380-9d5d-11eb-8491-2de7f2f5aaaf.jpg)

**Comment by melink14** [comment] 2021-04-14 11:30
Thanks for filing.

I've noticed this as well but hadn't filed since first line was usually enough.

My guess is that the non standard text box translate has invented isn't matching the position of the curosr.

Might be hard to fix while not breaking other sites but it's worth tracking!

**Comment by melink14** [comment] 2021-05-03 13:54
@all-contributors please add @Baardman82 for bugs

**Comment by melink14** [comment] 2022-02-28 12:16
This turned out to be the same as another issue caused by incorrect copying of text area styles when emulating for mouse over purposes so I'll dupe to that one which I plan to fix soon.

Duplicate of #672

**Closed by melink14** 2022-02-28 12:16 UTC
Labels: bug, P2, medium difficulty, detection
