### ISSUE TITLE
Trivial typo in the explanation of びっくり（吃驚） - to be surprise -> to be surprised

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#95] opened 2015-06-13 01:10 UTC
```
What steps will reproduce the problem?
//Hover over the word びっくり, 吃驚, 喫驚, or ビックリ

What is the expected output? What do you see instead?
//To be surprised. To be surprise.

What version of the product are you using? On what operating system?
//version 0.8.7 on Windows 8.1

Please provide any additional information below.
//This is really trivial and harmless, hope I posted it in the right place.
```

Original issue reported on code.google.com by `DantezNe...@gmail.com` on 31 Jan 2014 at 3:19

**Comment by melink14** [comment] 2020-07-26 03:10
Duplicate of #49

**Closed by melink14** 2020-07-26 03:10 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
