### ISSUE TITLE
<span> styling with !important overrides CSS from Rikai-kun

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#96] opened 2015-06-13 01:10 UTC
```
What steps will reproduce the problem?
1. Define a style in "span" for the main page
2. If any of the CSS styles have "!important" they will override the Rikai-kun 
color stylings
3.

What is the expected output? What do you see instead?
Expected output would be the colors defined in the CSS. What I see instead is 
the stylings defined on the main page if it has any "!important" styles defined 
for the span tag.

What version of the product are you using? On what operating system?
Mac OS X   10.9.2
Chrome     33.0.1750.152
Rikai-kun  0.8.9

Please provide any additional information below.
I've created an example HTML file to display the problem.
It's also live on my web server: http://www.standingmist.com/rikaikun/
```

Original issue reported on code.google.com by `ikari7...@gmail.com` on 16 Mar 2014 at 12:53

Attachments:
- [index.html](https://storage.googleapis.com/google-code-attachments/rikaikun/issue-96/comment-0/index.html)

**Comment by melink14** [comment] 2020-08-25 02:39
Duplicate of #221

**Closed** 2020-08-25 02:40 UTC
Labels: P2, Type-Defect, auto-migrated
