### ISSUE TITLE
Add explanations for abbr in names diction (and other places?)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#98] opened 2015-06-13 01:10 UTC
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


Please use labels and text to provide additional information.

```

Original issue reported on code.google.com by `melin...@gmail.com` on 21 Mar 2014 at 5:12

**Comment by melink14** [comment] 2019-09-23 06:14
Duplicate of #144

**Closed by melink14** 2019-09-23 06:14 UTC
Labels: Priority-Medium, Type-Enhancement, auto-migrated
