### ISSUE TITLE
Keyboard shortcut to toggle rikaikun

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#9] opened 2015-06-13 01:08 UTC
```
Currently, you have to click a button to turn rikaichan on and off.  Some 
people like keyboard shortcuts, so I think I will make one.

Besides, the original had one, it was even configurable.  The maturity of the 
firefox platform definitely shows.
```

Original issue reported on code.google.com by `melin...@gmail.com` on 6 Jan 2010 at 12:14

**Comment by melink14** [comment] 2020-08-19 00:26
There's a newer issue with more modern discussion so I'm going to dupe this one to that one.

Duplicate of #118

**Closed by melink14** 2020-08-19 00:26 UTC
Labels: Milestone-Release1.0, P2, Type-Enhancement, auto-migrated

**Comment by melink14** [comment] 2020-08-19 00:28
Duplicate of #118
