### ISSUE TITLE
Basic Documentation is Needed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melink14/rikaikun#8] opened 2015-06-13 01:08 UTC
```
Use the wiki to create some basic documentation about the project.  It's 
pretty simplistic from a user point of view, but I think it's important to 
have something.
```

Original issue reported on code.google.com by `melin...@gmail.com` on 5 Jan 2010 at 9:06

**Comment by melink14** [comment] 2020-09-04 07:47
Duplicate of #156

**Closed by melink14** 2020-09-04 07:47 UTC
Labels: P1, Type-Enhancement, auto-migrated
